Blockly.defineBlocksWithJsonArray([
  {
    "type": "pin_digital_write",
    "message0": "%{BKY_KB_MAIPLUS_PIN_DIGITAL_WRITE}",
    "args0": [
      {
        "type": "input_value",
        "name": "value",
        "check": [
          "Boolean",
          "Number",
        ],
      },
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "D0", "26" ],
          [ "D1", "13" ],
          [ "D2", "14" ],
          [ "D3", "15" ],
          [ "D4", "27" ],
          [ "D5", "32" ],
          [ "D6", "33" ],
        ],
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": "#E74C3C",
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "pin_digital_read",
    "message0": "%{BKY_KB_MAIPLUS_PIN_DIGITAL_READ}",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "D0", "26" ],
          [ "D1", "13" ],
          [ "D2", "14" ],
          [ "D3", "15" ],
          [ "D4", "27" ],
          [ "D5", "32" ],
          [ "D6", "33" ],
        ],
      },
    ],
    "output": [
      "Number",
      "Boolean",
    ],
    "inputsInline": true,
    "colour": "#E74C3C",
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "pin_analog_read",
    "message0": "%{BKY_KB_MAIPLUS_PIN_ANALOG_READ}",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "VR", "34" ],
          [ "A0", "26" ],
          [ "A1", "13" ],
          [ "A2", "14" ],
          [ "A3", "15" ],
          [ "A4", "27" ],
          [ "A5", "32" ],
          [ "A6", "33" ],
        ],
      },
    ],
    "output": "Number",
    "inputsInline": true,
    "colour": "#E74C3C",
    "tooltip": "%{BKY_KB_MAIPLUS_PIN_ANALOG_READ_TOOLTIP}",
    "helpUrl": "",
  },
  {
    "type": "pin_analog_write",
    "message0": "%{BKY_KB_MAIPLUS_PIN_ANALOG_WRITE}",
    "args0": [
      {
        "type": "input_value",
        "name": "value",
        "check": "Number",
      },
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "D0", "26" ],
          [ "D1", "13" ],
          [ "D2", "14" ],
          [ "D3", "15" ],
          [ "D4", "27" ],
          [ "D5", "32" ],
        ],
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": "#E74C3C",
    "tooltip": "%{BKY_KB_MAIPLUS_PIN_ANALOG_WRITE_TOOLTIP}",
    "helpUrl": "",
  },
])