Blockly.defineBlocksWithJsonArray([
  {
    "type": "camera_width",
    "message0": "%{BKY_KB_MAIPLUS_CAMERA_WIDTH}",
    "output": "Number",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "camera_height",
    "message0": "%{BKY_KB_MAIPLUS_CAMERA_HEIGHT}",
    "output": "Number",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "camera_resolution",
    "message0": "%{BKY_KB_MAIPLUS_CAMERA_RESOLUTION}",
    "args0": [
      {
        "type": "input_dummy",
      },
      {
        "type": "input_value",
        "name": "width",
        "check": "Number",
      },
      {
        "type": "input_value",
        "name": "height",
        "check": "Number",
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "camera_capture",
    "message0": "%{BKY_KB_MAIPLUS_CAMERA_CAPTURE}",
    "inputsInline": true,
    "output": "Image",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "camera_close",
    "message0": "%{BKY_KB_MAIPLUS_CAMERA_CLOSE}",
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
])
