Blockly.defineBlocksWithJsonArray([
  {
    "type": "pin_digital_write",
    "message0": "%{BKY_KB_MAI_PIN_DIGITAL_WRITE}",
    "args0": [
      {
        "type": "input_value",
        "name": "value",
        "check": [
          "Boolean",
          "Number",
        ],
      },
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_26}", "26" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_13}", "13" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_14}", "14" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_15}", "15" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_27}", "27" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_32}", "32" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_WRITE_OPT_33}", "33" ],
        ],
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": "#E74C3C",
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "pin_digital_read",
    "message0": "%{BKY_KB_MAI_PIN_DIGITAL_READ}",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_26}", "26" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_13}", "13" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_14}", "14" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_15}", "15" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_27}", "27" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_32}", "32" ],
          [ "%{BKY_KB_MAI_PIN_DIGITAL_READ_OPT_33}", "33" ],
        ],
      },
    ],
    "output": [
      "Number",
      "Boolean",
    ],
    "inputsInline": true,
    "colour": "#E74C3C",
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "pin_analog_read",
    "message0": "%{BKY_KB_MAI_PIN_ANALOG_READ}",
    "args0": [
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_34}", "34" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_26}", "26" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_13}", "13" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_14}", "14" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_15}", "15" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_27}", "27" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_32}", "32" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_READ_OPT_33}", "33" ],
        ],
      },
    ],
    "output": "Number",
    "inputsInline": true,
    "colour": "#E74C3C",
    "tooltip": "%{BKY_KB_MAI_PIN_ANALOG_READ_TOOLTIP}",
    "helpUrl": "",
  },
  {
    "type": "pin_analog_write",
    "message0": "%{BKY_KB_MAI_PIN_ANALOG_WRITE}",
    "args0": [
      {
        "type": "input_value",
        "name": "value",
        "check": "Number",
      },
      {
        "type": "field_dropdown",
        "name": "pin",
        "options": [
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_26}", "26" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_13}", "13" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_14}", "14" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_15}", "15" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_27}", "27" ],
          [ "%{BKY_KB_MAI_PIN_ANALOG_WRITE_OPT_32}", "32" ],
        ],
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": "#E74C3C",
    "tooltip": "%{BKY_KB_MAI_PIN_ANALOG_WRITE_TOOLTIP}",
    "helpUrl": "",
  },
])