Blockly.defineBlocksWithJsonArray([
  {
    "type": "maix3_camera_width",
    "message0": "%{BKY_KB_MAI_MAIX3_CAMERA_WIDTH}",
    "output": "Number",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "maix3_camera_height",
    "message0": "%{BKY_KB_MAI_MAIX3_CAMERA_HEIGHT}",
    "output": "Number",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "maix3_camera_resolution",
    "message0": "%{BKY_KB_MAI_MAIX3_CAMERA_RESOLUTION}",
    "args0": [
      {
        "type": "input_dummy",
      },
      {
        "type": "input_value",
        "name": "width",
        "check": "Number",
      },
      {
        "type": "input_value",
        "name": "height",
        "check": "Number",
      },
    ],
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "maix3_camera_capture",
    "message0": "%{BKY_KB_MAI_MAIX3_CAMERA_CAPTURE}",
    "inputsInline": true,
    "output": "Image",
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
  {
    "type": "maix3_camera_close",
    "message0": "%{BKY_KB_MAI_MAIX3_CAMERA_CLOSE}",
    "inputsInline": true,
    "previousStatement": null,
    "nextStatement": null,
    "colour": 20,
    "tooltip": "",
    "helpUrl": "",
  },
])
