export default {
  id: "kidbright-mai-plus",
  name: "KidBright uAI plus",
  description: "บอร์ดสมองกลเพื่อการเรียนรู้ปัญญาประดิษฐ์",
  wsUrl: "ws://10.150.36.1:7899",
  wsShell: "wss://10.150.36.1:5050",
  camera: {
    type: "mjpeg",
    port: 8000,
  },
  image: "images/board.png",
  protocol: "websocket-shell",
  version: "1.0.0",
  chip: "RISC-V",
  firmware: [],
  usb: [
    {
      vendorId: 0x18d1,
      productId: 0x0002,
    },
  ],
  blocks: [
    "blocks/blocks_basic.js",
    "blocks/blocks_camera.js",
    "blocks/blocks_display.js",
    "blocks/blocks_image.js",
    "blocks/blocks_gpio.js",
    "blocks/blocks_ai.js",
    "blocks/generators_basic.js",
    "blocks/generators_image.js",
    "blocks/generators_camera.js",
    "blocks/generators_display.js",
    "blocks/generators_gpio.js",
    "blocks/generators_ai.js",
    "blocks/blocks_maix_v4.js",
    "blocks/generators_maix_v4.js",
  ],
  autoCompletion: {},
}
